import type { SwipeCandidate, Match, Message } from '@/models';

export const DEMO_CANDIDATES: SwipeCandidate[] = [
  {
    company: {
      id: 'demo-c1',
      brandName: 'Vertex AI Solutions',
      legalName: 'Vertex AI Solutions Inc.',
      industry: 'Artificial Intelligence',
      hqLocation: 'San Francisco, CA',
      employeeRange: '51-200',
      description: 'Enterprise AI platform providing predictive analytics, NLP, and computer vision solutions for Fortune 500 companies.',
      offerings: ['Predictive Analytics', 'NLP Platform', 'Computer Vision API', 'MLOps Consulting'],
      needs: ['Sales Channel Partners', 'Cloud Infrastructure', 'Data Labeling Services'],
      offeringSummary: 'Enterprise-grade AI/ML platform with predictive analytics, NLP, and computer vision APIs.',
      needsSummary: 'Seeking strategic sales channel partners and cloud infrastructure providers to scale globally.',
      verificationBadges: ['identity-verified', 'documents-verified'],
      responseSpeed: 'fast',
      geographies: ['North America', 'Europe'],
      mutualConnections: [
        { type: 'event', label: 'SaaStr Annual 2025' },
        { type: 'accelerator', label: 'Y Combinator S23' },
      ],
      aiScoreBreakdown: { intentOverlap: 38, geoFit: 28, stageFit: 18, verificationBonus: 8 },
    },
    matchReasons: [
      { icon: '🎯', label: 'High Intent Overlap', description: 'Their AI platform needs align with your consulting capabilities' },
      { icon: '🌍', label: 'Geo Match', description: 'Both active in North America and Europe' },
      { icon: '📈', label: 'Growth Stage Fit', description: 'Similar company size enables equal partnership dynamics' },
    ],
    matchScore: 92,
  },
  {
    company: {
      id: 'demo-c2',
      brandName: 'GreenSupply Co',
      legalName: 'GreenSupply Co Ltd.',
      industry: 'Sustainable Supply Chain',
      hqLocation: 'Amsterdam, Netherlands',
      employeeRange: '201-500',
      description: 'End-to-end sustainable supply chain management platform helping businesses reduce carbon footprint while optimizing logistics costs.',
      offerings: ['Carbon Tracking Platform', 'Sustainable Sourcing Network', 'ESG Reporting Tools', 'Green Logistics Optimization'],
      needs: ['Technology Partners', 'Last-Mile Delivery', 'Warehouse Automation'],
      offeringSummary: 'Sustainable supply chain platform with carbon tracking, ESG reporting, and green logistics optimization.',
      needsSummary: 'Looking for technology partners to integrate warehouse automation and last-mile delivery solutions.',
      verificationBadges: ['identity-verified', 'documents-verified', 'premium-verified'],
      responseSpeed: 'fast',
      geographies: ['Europe', 'Asia Pacific'],
      mutualConnections: [
        { type: 'event', label: 'Davos ESG Summit 2025' },
        { type: 'partner', label: 'Shared: SAP Ecosystem' },
      ],
      aiScoreBreakdown: { intentOverlap: 35, geoFit: 22, stageFit: 20, verificationBonus: 11 },
    },
    matchReasons: [
      { icon: '🌱', label: 'ESG Synergy', description: 'Strong alignment on sustainability goals and green tech' },
      { icon: '🤝', label: 'Complementary Stack', description: 'Their logistics platform + your tech creates a full solution' },
      { icon: '⭐', label: 'Premium Verified', description: 'Fully vetted company with strong track record' },
    ],
    matchScore: 88,
  },
  {
    company: {
      id: 'demo-c3',
      brandName: 'FinEdge Partners',
      legalName: 'FinEdge Partners LLC',
      industry: 'Financial Technology',
      hqLocation: 'London, UK',
      employeeRange: '51-200',
      description: 'Next-generation payment infrastructure for B2B transactions. Real-time cross-border payments with built-in compliance.',
      offerings: ['B2B Payment Gateway', 'Cross-Border Settlements', 'KYB/AML Compliance Engine', 'Invoice Factoring API'],
      needs: ['ERP Integration Partners', 'Banking Relationships', 'Market Expansion in APAC'],
      offeringSummary: 'B2B payment infrastructure with cross-border settlements, compliance automation, and invoice factoring.',
      needsSummary: 'Seeking ERP integration partners and banking relationships to expand into the APAC market.',
      verificationBadges: ['identity-verified'],
      responseSpeed: 'moderate',
      geographies: ['Europe', 'North America', 'Asia Pacific'],
      mutualConnections: [
        { type: 'event', label: 'Money20/20 Europe 2025' },
      ],
      aiScoreBreakdown: { intentOverlap: 34, geoFit: 26, stageFit: 18, verificationBonus: 7 },
    },
    matchReasons: [
      { icon: '💰', label: 'Payment Synergy', description: 'Their payment infra can power your platform transactions' },
      { icon: '🌏', label: 'APAC Expansion', description: 'Mutual interest in Asia Pacific market growth' },
      { icon: '🔒', label: 'Compliance Ready', description: 'Built-in KYB/AML reduces partnership integration risk' },
    ],
    matchScore: 85,
  },
  {
    company: {
      id: 'demo-c4',
      brandName: 'CloudForge',
      legalName: 'CloudForge Technologies Inc.',
      industry: 'Cloud Infrastructure',
      hqLocation: 'Austin, TX',
      employeeRange: '501-1000',
      description: 'Multi-cloud orchestration platform that simplifies hybrid cloud management. Kubernetes-native with built-in security and cost optimization.',
      offerings: ['Multi-Cloud Orchestration', 'Kubernetes Management', 'Cloud Cost Optimizer', 'Zero-Trust Security Layer'],
      needs: ['AI/ML Workload Partners', 'Channel Resellers', 'Professional Services Network'],
      offeringSummary: 'Multi-cloud orchestration with Kubernetes management, cost optimization, and zero-trust security.',
      needsSummary: 'Looking for AI/ML workload partners and channel resellers to drive enterprise adoption.',
      verificationBadges: ['identity-verified', 'documents-verified'],
      responseSpeed: 'fast',
      geographies: ['North America', 'Europe', 'Middle East'],
      mutualConnections: [
        { type: 'investor', label: 'Shared investor: Sequoia Capital' },
        { type: 'event', label: 'AWS re:Invent 2024' },
      ],
      aiScoreBreakdown: { intentOverlap: 36, geoFit: 27, stageFit: 19, verificationBonus: 8 },
    },
    matchReasons: [
      { icon: '☁️', label: 'Infrastructure Fit', description: 'Their cloud platform perfectly hosts your SaaS workloads' },
      { icon: '📊', label: 'Cost Optimization', description: 'Potential 30-40% cloud cost reduction for your operations' },
      { icon: '🛡️', label: 'Security First', description: 'Zero-trust architecture aligns with enterprise compliance needs' },
    ],
    matchScore: 90,
  },
  {
    company: {
      id: 'demo-c5',
      brandName: 'TalentBridge',
      legalName: 'TalentBridge Global Inc.',
      industry: 'HR Technology',
      hqLocation: 'Berlin, Germany',
      employeeRange: '11-50',
      description: 'AI-powered talent matching platform connecting companies with pre-vetted remote engineering teams. Specializing in emerging market talent.',
      offerings: ['Remote Team Matching', 'Technical Vetting Platform', 'Employer of Record (EOR)', 'Team Augmentation'],
      needs: ['Enterprise Clients', 'Payroll Infrastructure', 'Learning & Development Platform'],
      offeringSummary: 'AI-driven talent matching with pre-vetted remote engineering teams and employer of record services.',
      needsSummary: 'Seeking enterprise clients and payroll infrastructure partners to scale remote team offerings.',
      verificationBadges: ['identity-verified'],
      responseSpeed: 'moderate',
      geographies: ['Europe', 'South America', 'Africa'],
      aiScoreBreakdown: { intentOverlap: 28, geoFit: 20, stageFit: 22, verificationBonus: 8 },
    },
    matchReasons: [
      { icon: '👥', label: 'Talent Pipeline', description: 'Access pre-vetted engineering talent for your growing team' },
      { icon: '💡', label: 'Startup Synergy', description: 'Both startups — lean partnership dynamics, fast decision making' },
      { icon: '🌍', label: 'Emerging Markets', description: 'Their talent network opens doors to new geographies' },
    ],
    matchScore: 78,
  },
  {
    company: {
      id: 'demo-c6',
      brandName: 'DataVault Pro',
      legalName: 'DataVault Pro Corp.',
      industry: 'Data Privacy & Compliance',
      hqLocation: 'Toronto, Canada',
      employeeRange: '51-200',
      description: 'Enterprise data governance platform ensuring GDPR, CCPA, and SOC 2 compliance. Automated data classification, consent management, and breach detection.',
      offerings: ['Data Governance Platform', 'Consent Management', 'Automated Compliance Audits', 'Breach Detection & Response'],
      needs: ['SaaS Integrations', 'Legal Advisory Network', 'EU Market Partners'],
      offeringSummary: 'Data governance platform with automated compliance audits, consent management, and breach detection.',
      needsSummary: 'Seeking SaaS integration partners and legal advisory networks to expand EU market presence.',
      verificationBadges: ['identity-verified', 'documents-verified', 'premium-verified'],
      responseSpeed: 'fast',
      geographies: ['North America', 'Europe'],
      mutualConnections: [
        { type: 'accelerator', label: 'Techstars Toronto 2024' },
      ],
      aiScoreBreakdown: { intentOverlap: 33, geoFit: 25, stageFit: 17, verificationBonus: 11 },
    },
    matchReasons: [
      { icon: '🔐', label: 'Compliance Synergy', description: 'Their governance platform ensures your data practices are compliant' },
      { icon: '⚡', label: 'Fast Responder', description: 'Known for quick turnaround — ideal for time-sensitive integrations' },
      { icon: '🏆', label: 'Premium Partner', description: 'Triple-verified with excellent industry reputation' },
    ],
    matchScore: 86,
  },
  {
    company: {
      id: 'demo-c7',
      brandName: 'LogiFlow',
      legalName: 'LogiFlow Logistics Inc.',
      industry: 'Logistics Technology',
      hqLocation: 'Singapore',
      employeeRange: '201-500',
      description: 'Real-time logistics visibility platform powering supply chain transparency for 500+ enterprise clients across Asia Pacific.',
      offerings: ['Real-Time Tracking Platform', 'Predictive ETA Engine', 'Customs Automation', 'Carrier Marketplace'],
      needs: ['Western Market Expansion', 'Cold Chain Partners', 'Insurance Providers'],
      offeringSummary: 'Real-time logistics visibility with predictive ETA, customs automation, and carrier marketplace.',
      needsSummary: 'Looking to expand into Western markets and partner with cold chain logistics and insurance providers.',
      verificationBadges: ['identity-verified', 'documents-verified'],
      responseSpeed: 'moderate',
      geographies: ['Asia Pacific', 'Middle East'],
      mutualConnections: [
        { type: 'event', label: 'Gartner Supply Chain 2025' },
        { type: 'partner', label: 'Shared: DHL Partner Network' },
      ],
      aiScoreBreakdown: { intentOverlap: 30, geoFit: 24, stageFit: 20, verificationBonus: 8 },
    },
    matchReasons: [
      { icon: '🚚', label: 'Logistics Network', description: 'Expand your delivery capabilities across APAC with their platform' },
      { icon: '📡', label: 'Real-Time Visibility', description: 'End-to-end tracking improves customer experience' },
      { icon: '🤝', label: 'Market Access', description: 'Gateway to 500+ enterprise clients in Asia Pacific' },
    ],
    matchScore: 82,
  },
  {
    company: {
      id: 'demo-c8',
      brandName: 'MedConnect Health',
      legalName: 'MedConnect Health Systems',
      industry: 'Healthcare Technology',
      hqLocation: 'Boston, MA',
      employeeRange: '201-500',
      description: 'HIPAA-compliant telemedicine platform with EHR integration, AI-assisted diagnostics, and remote patient monitoring for healthcare providers.',
      offerings: ['Telemedicine Platform', 'EHR Integration Suite', 'AI Diagnostic Assist', 'Remote Patient Monitoring'],
      needs: ['Wearable Device Partners', 'Insurance API Providers', 'International Expansion'],
      offeringSummary: 'HIPAA-compliant telemedicine with EHR integration, AI diagnostics, and remote patient monitoring.',
      needsSummary: 'Seeking wearable device partners and insurance API providers for comprehensive care solutions.',
      verificationBadges: ['identity-verified', 'documents-verified', 'premium-verified'],
      responseSpeed: 'fast',
      geographies: ['North America'],
      mutualConnections: [
        { type: 'investor', label: 'Shared investor: a16z Bio' },
        { type: 'event', label: 'HIMSS Annual Conference 2025' },
      ],
      aiScoreBreakdown: { intentOverlap: 31, geoFit: 22, stageFit: 20, verificationBonus: 11 },
    },
    matchReasons: [
      { icon: '🏥', label: 'Healthcare Innovation', description: 'AI health-tech is a high-growth vertical for B2B partnerships' },
      { icon: '🔗', label: 'Integration Ready', description: 'Open API architecture makes partnership integration seamless' },
      { icon: '⭐', label: 'Top Rated', description: 'Premium-verified with fastest response speed in healthcare' },
    ],
    matchScore: 84,
  },
  {
    company: {
      id: 'demo-c9',
      brandName: 'ScaleOps',
      legalName: 'ScaleOps Inc.',
      industry: 'RevOps & Sales Intelligence',
      hqLocation: 'New York, NY',
      employeeRange: '11-50',
      description: 'AI-driven revenue operations platform that unifies CRM data, pipeline forecasting, and sales coaching in a single workspace for B2B sales teams.',
      offerings: ['Pipeline Intelligence', 'CRM Data Enrichment', 'AI Sales Coaching', 'Revenue Forecasting'],
      needs: ['CRM Integration Partners', 'Enterprise Pilots', 'Channel Resellers'],
      offeringSummary: 'Revenue operations platform with AI pipeline intelligence, CRM enrichment, and sales coaching.',
      needsSummary: 'Seeking CRM integration partners and enterprise clients to expand market coverage.',
      verificationBadges: ['identity-verified', 'documents-verified'],
      responseSpeed: 'fast',
      geographies: ['North America', 'Europe'],
      mutualConnections: [
        { type: 'event', label: 'Dreamforce 2025' },
        { type: 'accelerator', label: 'NYC VC Cohort 2024' },
      ],
      aiScoreBreakdown: { intentOverlap: 32, geoFit: 28, stageFit: 19, verificationBonus: 8 },
    },
    matchReasons: [
      { icon: '📊', label: 'RevOps Fit', description: 'Their pipeline intelligence directly amplifies your sales output' },
      { icon: '🔌', label: 'CRM Synergy', description: 'Deep Salesforce and HubSpot integrations — zero friction adoption' },
      { icon: '🚀', label: 'Startup Stage', description: 'Lean team, fast decisions, strong founder-to-founder energy' },
    ],
    matchScore: 87,
  },
  {
    company: {
      id: 'demo-c10',
      brandName: 'CyberShield AI',
      legalName: 'CyberShield AI Ltd.',
      industry: 'Cybersecurity',
      hqLocation: 'Tel Aviv, Israel',
      employeeRange: '51-200',
      description: 'Next-gen threat detection platform using behavioral AI to protect enterprise infrastructure. 99.97% detection rate with under 0.1% false positives.',
      offerings: ['Behavioral Threat Detection', 'Zero-Day Attack Prevention', 'SOC Automation', 'Threat Intelligence Feed'],
      needs: ['MSSP Partners', 'Enterprise Sales', 'US Market Expansion'],
      offeringSummary: 'AI-powered threat detection with zero-day prevention, SOC automation, and real-time threat intelligence.',
      needsSummary: 'Seeking MSSP partners and enterprise sales channels to accelerate US market expansion.',
      verificationBadges: ['identity-verified', 'documents-verified', 'premium-verified'],
      responseSpeed: 'fast',
      geographies: ['Europe', 'North America', 'Middle East'],
      mutualConnections: [
        { type: 'event', label: 'RSA Conference 2025' },
        { type: 'investor', label: 'Shared investor: Insight Partners' },
      ],
      aiScoreBreakdown: { intentOverlap: 36, geoFit: 24, stageFit: 18, verificationBonus: 11 },
    },
    matchReasons: [
      { icon: '🛡️', label: 'Security Partnership', description: 'Bundle their AI threat detection with your SaaS for enterprise deals' },
      { icon: '🌐', label: 'US Expansion Ready', description: 'They need exactly what you offer — market access and distribution' },
      { icon: '🏆', label: 'Award-Winning Tech', description: 'Gartner Cool Vendor 2024 — credibility multiplier for co-sells' },
    ],
    matchScore: 89,
  },
  {
    company: {
      id: 'demo-c11',
      brandName: 'Nexara Commerce',
      legalName: 'Nexara Commerce Pte. Ltd.',
      industry: 'B2B E-Commerce',
      hqLocation: 'Dubai, UAE',
      employeeRange: '201-500',
      description: 'Wholesale B2B marketplace for MENA and South Asia enabling manufacturers to connect directly with buyers, cutting middlemen and reducing procurement costs by 40%.',
      offerings: ['B2B Wholesale Marketplace', 'Procurement Automation', 'Trade Finance', 'Supplier Verification Network'],
      needs: ['Logistics Partners', 'Payment Gateway', 'European Market Entry'],
      offeringSummary: 'B2B wholesale marketplace with procurement automation, trade finance, and supplier verification.',
      needsSummary: 'Seeking logistics and payment partners to expand into European markets.',
      verificationBadges: ['identity-verified', 'documents-verified'],
      responseSpeed: 'moderate',
      geographies: ['Middle East', 'Asia Pacific', 'Europe'],
      mutualConnections: [
        { type: 'event', label: 'GITEX Global 2025' },
      ],
      aiScoreBreakdown: { intentOverlap: 29, geoFit: 26, stageFit: 19, verificationBonus: 8 },
    },
    matchReasons: [
      { icon: '🛒', label: 'Commerce Infrastructure', description: 'Their marketplace is hungry for your payment and logistics stack' },
      { icon: '🌍', label: 'MENA Gateway', description: 'Unblock access to 200M+ buyers in Middle East and South Asia' },
      { icon: '💸', label: 'Trade Finance Ready', description: 'Built-in financing means faster deal cycles for both sides' },
    ],
    matchScore: 82,
  },
  {
    company: {
      id: 'demo-c12',
      brandName: 'EduStack Pro',
      legalName: 'EduStack Professional Learning Corp.',
      industry: 'Enterprise Learning & Development',
      hqLocation: 'Sydney, Australia',
      employeeRange: '51-200',
      description: 'Corporate upskilling platform delivering AI-personalized learning paths for technical and leadership skills. 3,000+ content modules from top universities and industry experts.',
      offerings: ['Personalized Learning Paths', 'Skills Gap Analysis', 'Manager Development Program', 'Compliance Training Automation'],
      needs: ['HR Tech Integrations', 'Content Partners', 'APAC Enterprise Clients'],
      offeringSummary: 'AI-personalized corporate learning with skills gap analysis, leadership programs, and compliance automation.',
      needsSummary: 'Seeking HR tech integration partners and enterprise clients to scale across APAC.',
      verificationBadges: ['identity-verified'],
      responseSpeed: 'moderate',
      geographies: ['Asia Pacific', 'Europe'],
      mutualConnections: [
        { type: 'partner', label: 'Shared: Workday Partner Network' },
        { type: 'accelerator', label: 'Antler AU Cohort 2024' },
      ],
      aiScoreBreakdown: { intentOverlap: 27, geoFit: 20, stageFit: 22, verificationBonus: 7 },
    },
    matchReasons: [
      { icon: '🎓', label: 'L&D Fit', description: 'Upskill your team on their platform — and resell to your clients' },
      { icon: '🔗', label: 'HRIS Integration', description: 'Plugs directly into Workday and SAP SuccessFactors ecosystems' },
      { icon: '📈', label: 'APAC Growth', description: 'Mutual expansion interest in fast-growing Pacific markets' },
    ],
    matchScore: 76,
  },
];

export const DEMO_MATCHES: Match[] = [
  {
    id: 'demo-match-1',
    companyAId: 'dev-company-001',
    companyBId: 'demo-c1',
    matchedCompany: {
      id: 'demo-c1',
      brandName: 'Vertex AI Solutions',
      industry: 'Artificial Intelligence',
      hqLocation: 'San Francisco, CA',
      offeringSummary: 'Enterprise-grade AI/ML platform with predictive analytics, NLP, and computer vision APIs.',
      needsSummary: 'Seeking strategic sales channel partners and cloud infrastructure providers.',
      verificationBadges: ['identity-verified', 'documents-verified'],
    },
    matchReasons: [
      { icon: '🎯', label: 'High Intent Overlap', description: 'Their AI platform needs align with your consulting capabilities' },
      { icon: '🌍', label: 'Geo Match', description: 'Both active in North America and Europe' },
    ],
    matchScore: 92,
    status: 'chatting',
    lastMessagePreview: 'Would love to explore a pilot integration!',
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 2,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-match-2',
    companyAId: 'dev-company-001',
    companyBId: 'demo-c2',
    matchedCompany: {
      id: 'demo-c2',
      brandName: 'GreenSupply Co',
      industry: 'Sustainable Supply Chain',
      hqLocation: 'Amsterdam, Netherlands',
      offeringSummary: 'Sustainable supply chain platform with carbon tracking and green logistics.',
      needsSummary: 'Looking for technology partners to integrate warehouse automation.',
      verificationBadges: ['identity-verified', 'documents-verified', 'premium-verified'],
    },
    matchReasons: [
      { icon: '🌱', label: 'ESG Synergy', description: 'Strong alignment on sustainability goals' },
      { icon: '🤝', label: 'Complementary Stack', description: 'Combined solution covers end-to-end supply chain' },
    ],
    matchScore: 88,
    status: 'new',
    unreadCount: 0,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-match-3',
    companyAId: 'dev-company-001',
    companyBId: 'demo-c4',
    matchedCompany: {
      id: 'demo-c4',
      brandName: 'CloudForge',
      industry: 'Cloud Infrastructure',
      hqLocation: 'Austin, TX',
      offeringSummary: 'Multi-cloud orchestration with Kubernetes management and cost optimization.',
      needsSummary: 'Looking for AI/ML workload partners and channel resellers.',
      verificationBadges: ['identity-verified', 'documents-verified'],
    },
    matchReasons: [
      { icon: '☁️', label: 'Infrastructure Fit', description: 'Cloud platform perfectly hosts SaaS workloads' },
      { icon: '📊', label: 'Cost Optimization', description: '30-40% potential cloud cost reduction' },
    ],
    matchScore: 90,
    status: 'meeting_scheduled',
    lastMessagePreview: 'Meeting confirmed for Thursday 2pm EST',
    lastMessageAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
];

const now = Date.now();
export const DEMO_MESSAGES: Record<string, Message[]> = {
  'demo-match-1': [
    {
      id: 'dm-1',
      matchId: 'demo-match-1',
      senderId: 'other-user',
      senderCompanyId: 'demo-c1',
      content: 'Hi! We noticed great synergy between our AI platform and your consulting services. Would love to explore collaboration.',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-2',
      matchId: 'demo-match-1',
      senderId: 'dev-bypass-user',
      senderCompanyId: 'dev-company-001',
      content: 'Absolutely! We\'ve been looking for an AI partner. Your predictive analytics API looks particularly relevant to our clients.',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-3',
      matchId: 'demo-match-1',
      senderId: 'other-user',
      senderCompanyId: 'demo-c1',
      content: 'Perfect. We have a reseller program that could work well. Here\'s our capability overview:',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-4',
      matchId: 'demo-match-1',
      senderId: 'other-user',
      senderCompanyId: 'demo-c1',
      content: 'Vertex AI Solutions — Enterprise Capability Deck\n\n• Predictive Analytics API (99.9% uptime SLA)\n• NLP Platform (40+ languages)\n• Computer Vision (real-time processing)\n• Full MLOps consulting & support',
      type: 'capability_deck',
      isRead: true,
      createdAt: new Date(now - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-5',
      matchId: 'demo-match-1',
      senderId: 'dev-bypass-user',
      senderCompanyId: 'dev-company-001',
      content: 'This looks impressive. Let me share this with our CTO. Could we schedule a technical deep-dive next week?',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-6',
      matchId: 'demo-match-1',
      senderId: 'other-user',
      senderCompanyId: 'demo-c1',
      content: 'Would love to explore a pilot integration!',
      type: 'text',
      isRead: false,
      createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-7',
      matchId: 'demo-match-1',
      senderId: 'other-user',
      senderCompanyId: 'demo-c1',
      content: 'We can offer a 60-day free POC for qualified partners. Interested?',
      type: 'text',
      isRead: false,
      createdAt: new Date(now - 1 * 60 * 60 * 1000).toISOString(),
    },
  ],
  'demo-match-3': [
    {
      id: 'dm-10',
      matchId: 'demo-match-3',
      senderId: 'other-user',
      senderCompanyId: 'demo-c4',
      content: 'Great match! We think our multi-cloud platform could significantly reduce your infrastructure costs.',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-11',
      matchId: 'demo-match-3',
      senderId: 'dev-bypass-user',
      senderCompanyId: 'dev-company-001',
      content: 'We\'re spending a lot on cloud right now. Would love to see a cost analysis.',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-12',
      matchId: 'demo-match-3',
      senderId: 'other-user',
      senderCompanyId: 'demo-c4',
      content: 'Here\'s our standard RFQ template — fill in your current infrastructure details and we\'ll prepare a custom proposal.\n\nRFQ: Cloud Infrastructure Optimization\n• Current monthly cloud spend: ___\n• Primary cloud provider(s): ___\n• Number of Kubernetes clusters: ___\n• Compliance requirements: ___',
      type: 'rfq_template',
      isRead: true,
      createdAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-13',
      matchId: 'demo-match-3',
      senderId: 'dev-bypass-user',
      senderCompanyId: 'dev-company-001',
      content: 'Filled and sent! Can we schedule a call to discuss?',
      type: 'text',
      isRead: true,
      createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'dm-14',
      matchId: 'demo-match-3',
      senderId: 'other-user',
      senderCompanyId: 'demo-c4',
      content: 'Meeting confirmed for Thursday 2pm EST',
      type: 'text',
      isRead: false,
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    },
  ],
};
